#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

readonly xrandr_status="$(xrandr)"

has_output() {
  echo "${xrandr_status}" | grep -q "^${1} connected"
}

setup_one_screen() {
  xrandr \
    --output "$1" \
      --primary \
      --mode "2560x1440" \
    --dpi 96
}

setup_two_screens() {
  xrandr \
    --output "$1" \
      --primary \
      --mode "2560x1440" \
    --output "$2" \
      --mode "2560x1440" \
      --right-of "$1" \
    --dpi 96
}

restart_wm() {
  i3-msg "restart" || true
}

main() {
  if (has_output eDP1) && (has_output HDMI1); then
    setup_two_screens "eDP1" "HDMI1"
    restart_wm
  elif (has_output eDP1) && (has_output DP1-2); then
    setup_two_screens "eDP1" "DP1-2"
    restart_wm
  else
    setup_one_screen "eDP1"
    restart_wm
  fi
}

main
