#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck disable=SC1091 source=./tyr-home-paths
# source "${SCRIPT_DIR}/tyr-home-paths"

load_xrandr_status() {
  xrandr
}

has_output() {
  local xrandr_status="${1}" screen_name="${2}"

  echo "${xrandr_status}" | grep -q "^${screen_name} connected"
}

setup_one_screen() {
  xrandr \
    --output "$1" \
      --primary \
      --mode "2560x1440" \
    --dpi 96
}

setup_two_screens() {
  xrandr \
    --output "$1" \
      --primary \
      --mode "2560x1440" \
    --output "$2" \
      --mode "2560x1440" \
      --left-of "$1" \
    --dpi 96
}
# --scale-from "2560x1440" \

restart_wm() {
  i3-msg "restart" || true
}

main() {
  local xrandr_status

  xrandr_status="$(load_xrandr_status)"

  if (has_output "${xrandr_status}" eDP-1) && (has_output "${xrandr_status}" HDMI-1); then
    setup_two_screens "eDP-1" "HDMI-1"
    restart_wm
  elif (has_output "${xrandr_status}" eDP-1) && (has_output "${xrandr_status}" DP-1-2); then
    setup_two_screens "eDP-1" "DP-1-2"
    restart_wm
  elif (has_output "${xrandr_status}" eDP1) && (has_output "${xrandr_status}" HDMI1); then
    setup_two_screens "eDP-1" "HDMI-1"
    restart_wm
  elif (has_output "${xrandr_status}" eDP1) && (has_output "${xrandr_status}" DP1-2); then
    setup_two_screens "eDP-1" "DP1-2"
    restart_wm
  else
    setup_one_screen "eDP-1"
    restart_wm
  fi
}

main
